NovTeam4/villager-service

build.gradle

- spring data jpa
- validation
- lombok
- h2 (테스트 DB)
- mysql

feat: 의존성 추가

---

src/main/java/com/example/villagerservice/config/security/context/MemberContext.java
src/main/java/com/example/villagerservice/config/security/service/CustomUserDetailService.java
src/main/java/com/example/villagerservice/member/api/MemberApiController.java
src/main/java/com/example/villagerservice/member/domain/Member.java
src/main/java/com/example/villagerservice/member/domain/MemberRepository.java
src/main/java/com/example/villagerservice/member/exception/MemberErrorCode.java
src/main/java/com/example/villagerservice/member/request/MemberCreate.java
src/main/java/com/example/villagerservice/member/request/MemberInfoUpdate.java
src/main/java/com/example/villagerservice/member/request/MemberPasswordUpdate.java
src/main/java/com/example/villagerservice/member/service/MemberService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberServiceImpl.java
src/main/java/com/example/villagerservice/member/valid/Password.java
src/main/java/com/example/villagerservice/member/valid/PasswordValidator.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java

* 2022 - 12 - 01 작성
- 회원 정보 변경 서비스 개발
- 회원 비밀번호 변경 서비스 개발
- 비밀번호 Custom Validation 추가

회원 정보 변경 서비스 개발 #9

---

src/main/java/com/example/villagerservice/common/exception/AuthErrorCode.java
src/main/java/com/example/villagerservice/common/exception/AuthVillagerException.java
src/main/java/com/example/villagerservice/config/security/handler/CustomFailureHandler.java
src/main/java/com/example/villagerservice/config/security/provider/CustomAuthenticationProvider.java
src/main/java/com/example/villagerservice/config/security/service/CustomUserDetailService.java
src/main/java/com/example/villagerservice/member/api/MemberApiController.java
src/main/java/com/example/villagerservice/member/domain/Member.java
src/main/java/com/example/villagerservice/member/exception/MemberErrorCode.java
src/main/java/com/example/villagerservice/member/service/MemberService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberServiceImpl.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java

- 2022 - 12 - 02 작성
- 회원 로그인 시 인증 예외 버그 수정
- 회원 탈퇴 서비스 개발
- 회원 탈퇴 테스트 작성

회원 탈퇴 기능 개발#10

---

src/main/java/com/example/villagerservice/common/utils/DeduplicationUtils.java
src/main/java/com/example/villagerservice/member/api/AuthApiController.java
src/main/java/com/example/villagerservice/member/api/MemberApiController.java
src/main/java/com/example/villagerservice/member/domain/Birthday.java
src/main/java/com/example/villagerservice/member/domain/Gender.java
src/main/java/com/example/villagerservice/member/domain/MannerPoint.java
src/main/java/com/example/villagerservice/member/domain/Member.java
src/main/java/com/example/villagerservice/member/domain/Tag.java
src/main/java/com/example/villagerservice/member/domain/TagCollection.java
src/main/java/com/example/villagerservice/member/exception/MemberErrorCode.java
src/main/java/com/example/villagerservice/member/request/MemberAddAttentionTag.java
src/main/java/com/example/villagerservice/member/request/MemberCreate.java
src/main/java/com/example/villagerservice/member/request/MemberLogin.java
src/main/java/com/example/villagerservice/member/service/MemberService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberServiceImpl.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerTest.java
src/test/java/com/example/villagerservice/member/domain/TagCollectionTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java

* 2022 - 12 - 03
- 회원 관심태그 도메인 개발
- 회원 관심태그 서비스 개발
- 회원 관심태그 예외 코드 추가
- 회원 관심태그 api 개발

회원 관심태그 기능 개발 #11

---

src/main/java/com/example/villagerservice/common/jwt/JwtTokenErrorCode.java
src/main/java/com/example/villagerservice/config/security/LocalSecurityConfig.java
src/main/java/com/example/villagerservice/config/security/filters/LocalJwtAuthenticationFilter.java
src/main/java/com/example/villagerservice/member/api/AuthApiController.java
src/main/java/com/example/villagerservice/member/service/AuthTokenService.java
src/main/java/com/example/villagerservice/member/service/impl/AuthTokenServiceImpl.java
src/main/resources/database/local/data.sql

- active profile local 추가
- api 테스트 시 기존에 회원가입 후 로그인해서 access_token을 발급받아야 했는데 이 부분에 기본적인 회원 정보를 넣어서 SecurityContextHolder의 SecurityContext에 있는 Authentication에 넣어서 해결했다.

Local Security 추가

---

build.gradle
src/main/java/com/example/villagerservice/config/jpa/QuerydslConfig.java
src/main/java/com/example/villagerservice/town/api/TownApiController.java
src/main/java/com/example/villagerservice/town/domain/Town.java
src/main/java/com/example/villagerservice/town/domain/TownQueryRepository.java
src/main/java/com/example/villagerservice/town/dto/TownList.java
src/main/java/com/example/villagerservice/town/dto/TownListDetail.java
src/main/java/com/example/villagerservice/town/infra/TownQueryRepositoryImpl.java
src/main/java/com/example/villagerservice/town/service/TownQueryService.java
src/main/java/com/example/villagerservice/town/service/impl/TownQueryServiceImpl.java
src/main/resources/data.sql
src/test/java/com/example/villagerservice/town/api/TownApiControllerTest.java

- 2022 - 12 - 05
- QueryDsl 라이브러리 추가, QueryDslConfig 추가
- 행정동, 법정동 중심좌표 excel 파일로 데이터베이스에 데이터 밀어넣었다.
- 근처동네 좌표 기반 조회 개발
- 근처동네 동,읍,면 이름 기반 조회 개발
- FE분들과 근처동네 조회 API 의논 필요

회원 동네 조회 개발#12

---

build.gradle
src/main/java/com/example/villagerservice/common/jwt/JwtTokenProvider.java
src/main/java/com/example/villagerservice/config/JasyptConfig.java
src/main/java/com/example/villagerservice/config/security/JwtLocalSecurityConfig.java
src/main/java/com/example/villagerservice/config/security/LocalSecurityConfig.java
src/main/java/com/example/villagerservice/config/security/SecurityConfig.java
src/main/java/com/example/villagerservice/config/security/filters/JwtAuthenticationFilter.java
src/main/java/com/example/villagerservice/member/domain/Member.java
src/test/java/com/example/villagerservice/BaseControllerTest.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerTest.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java
src/test/java/com/example/villagerservice/party/service/impl/PartyListServiceImplTest.java

- Spring Rest Docs 라이브러리 추가
- Swagger UI 라이브러리 추가
- 컨트롤러 테스트 부분 다시 작성해야함

Spring rest docs

---

src/main/java/com/example/villagerservice/member/api/MemberApiController.java
src/main/java/com/example/villagerservice/member/domain/MemberDetailRepository.java
src/main/java/com/example/villagerservice/member/dto/CreateMember.java
src/main/java/com/example/villagerservice/member/dto/ValidMemberNickname.java
src/main/java/com/example/villagerservice/member/exception/MemberErrorCode.java
src/main/java/com/example/villagerservice/member/service/MemberService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberServiceImpl.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerTest.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java

- 회원 가입 시 닉네임 유효성 검사 로직 추가
- 회원 닉네임 유효성 검사 api 추가

회원 닉네임 유효성 검사 추가

---

src/main/java/com/example/villagerservice/member/api/AuthApiController.java
src/main/java/com/example/villagerservice/town/dto/TownList.java
src/main/java/com/example/villagerservice/town/infra/TownQueryRepositoryImpl.java
src/test/java/com/example/document/BaseDocumentation.java
src/test/java/com/example/villagerservice/config/BaseLogin.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerTest.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/town/api/TownApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/town/api/TownApiControllerTest.java
src/test/java/com/example/villagerservice/town/service/impl/TownQueryServiceImplTest.java

- AWS RDS에 동네 데이터 밀어넣음
- Swagger에서는 Get 요청 시 MessageBody에 데이터를 넣을 수 없어서 Postman으로 테스트해야함
- 근처동네 데이터는 40개로 반환하도록 개발

회원 근처동네 조회 #12

---

src/main/java/com/example/villagerservice/common/exception/CommonErrorCode.java
src/main/java/com/example/villagerservice/common/exception/GlobalExceptionHandler.java
src/main/java/com/example/villagerservice/member/api/MemberTownApiController.java
src/main/java/com/example/villagerservice/member/service/MemberTownService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberTownServiceImpl.java
src/test/java/com/example/document/RestDocumentationTemplate.java
src/test/java/com/example/villagerservice/member/api/MemberTownApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/MemberTownApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberTownServiceImplTest.java
src/test/java/com/example/villagerservice/party/api/PartyApiControllerTest.java

- 2022 - 12 - 09
- 회원 동네 삭제 서비스 개발
- 회원 동네 삭제 테스트 작성
- GlobalExceptionHandler에 예외 추가(HttpRequestMethodNotSupportedException, Exception)

회원 동네 삭제 개발 #15

---

src/main/java/com/example/villagerservice/common/utils/DateCalculateConverter.java
src/main/java/com/example/villagerservice/common/utils/StringConverter.java
src/main/java/com/example/villagerservice/member/api/MemberTownApiController.java
src/main/java/com/example/villagerservice/member/domain/MemberTown.java
src/main/java/com/example/villagerservice/member/domain/MemberTownQueryRepository.java
src/main/java/com/example/villagerservice/member/domain/MemberTownRepository.java
src/main/java/com/example/villagerservice/member/dto/FindMemberTownDetail.java
src/main/java/com/example/villagerservice/member/dto/FindMemberTownList.java
src/main/java/com/example/villagerservice/member/dto/MemberTownListItem.java
src/main/java/com/example/villagerservice/member/exception/MemberErrorCode.java
src/main/java/com/example/villagerservice/member/infra/MemberTownQueryRepositoryImpl.java
src/main/java/com/example/villagerservice/member/service/MemberTownQueryService.java
src/main/java/com/example/villagerservice/member/service/MemberTownService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberTownQueryServiceImpl.java
src/main/java/com/example/villagerservice/member/service/impl/MemberTownServiceImpl.java
src/test/java/com/example/document/RestDocumentationTemplate.java
src/test/java/com/example/villagerservice/member/api/MemberTownApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/MemberTownApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberTownQueryServiceImplTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberTownServiceImplTest.java
src/test/java/com/example/villagerservice/party/api/PartyApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/town/api/TownApiControllerIntegratedTest.java

- 2022 - 12 - 10
- 회원동네 조회 서비스 개발
- 회원동네 조회 테스트 작성
- 테스트 코드 부분 수정

#66 회원 등록된 동네 조회 기능 개발 

---

src/main/java/com/example/villagerservice/follow/api/FollowApiController.java
src/main/java/com/example/villagerservice/follow/domain/Follow.java
src/main/java/com/example/villagerservice/follow/domain/FollowRepository.java
src/main/java/com/example/villagerservice/follow/exception/FollowErrorCode.java
src/main/java/com/example/villagerservice/follow/exception/FollowException.java
src/main/java/com/example/villagerservice/follow/service/FollowService.java
src/main/java/com/example/villagerservice/follow/service/impl/FollowServiceImpl.java
src/test/java/com/example/villagerservice/follow/api/FollowApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/follow/api/FollowApiControllerTest.java
src/test/java/com/example/villagerservice/follow/service/impl/FollowServiceImplTest.java

- 2022 - 12 -11
- 회원 팔로우 기능 개발
- 회워 팔로우 테스트 작성

#6 회원 팔로우 추가 기능 개발 

---

src/main/java/com/example/villagerservice/config/security/SecurityConfig.java

Spring Security CORS 설정

---

src/main/java/com/example/villagerservice/config/redis/RedisRepository.java
src/main/java/com/example/villagerservice/config/redis/RedisRepositoryImpl.java
src/main/java/com/example/villagerservice/member/api/AuthApiController.java
src/main/java/com/example/villagerservice/member/service/AuthTokenService.java
src/main/java/com/example/villagerservice/member/service/impl/AuthTokenServiceImpl.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerTest.java

- 로그아웃 서비스 기능 추가
- 로그아웃 테스트 작성
- Redis Repository deleteRefreshToken 메서드 추가

로그아웃 기능 추가

---

src/main/java/com/example/villagerservice/config/properties/CorsProperties.java
src/main/java/com/example/villagerservice/config/security/SecurityConfig.java
src/main/java/com/example/villagerservice/post/domain/Category.java
src/main/java/com/example/villagerservice/postlike/api/PostLikeApiController.java
src/main/java/com/example/villagerservice/postlike/domain/PostLike.java
src/main/java/com/example/villagerservice/postlike/domain/PostLikeRepository.java
src/main/java/com/example/villagerservice/postlike/service/PostLikeService.java
src/main/java/com/example/villagerservice/postlike/service/impl/PostLikeServiceImpl.java
src/test/java/com/example/villagerservice/config/BaseLogin.java
src/test/java/com/example/villagerservice/follow/api/FollowApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/party/api/PartyApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/party/api/PartyApiControllerTest.java
src/test/java/com/example/villagerservice/postlike/api/PostLikeApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/postlike/api/PostLikeApiControllerTest.java
src/test/java/com/example/villagerservice/postlike/service/impl/PostLikeServiceImplTest.java

- 게시글 좋아요 서비스 개발
- 게시글 좋아요 테스트 작성
- cors 설정 변경, 버그 수정

게시글 좋아요 기능 추가

---

src/main/java/com/example/villagerservice/postlike/api/PostLikeApiController.java
src/main/java/com/example/villagerservice/postlike/domain/PostLikeRepository.java
src/main/java/com/example/villagerservice/postlike/exception/PostLikeErrorCode.java
src/main/java/com/example/villagerservice/postlike/exception/PostLikeException.java
src/main/java/com/example/villagerservice/postlike/service/PostLikeService.java
src/main/java/com/example/villagerservice/postlike/service/impl/PostLikeServiceImpl.java
src/test/java/com/example/villagerservice/postlike/api/PostLikeApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/postlike/api/PostLikeApiControllerTest.java
src/test/java/com/example/villagerservice/postlike/service/impl/PostLikeServiceImplTest.java

- 게시글 좋아요 해제 서비스 개발
- 게시글 좋아요 해제 테스트 작성

게시글 좋아요 해제 서비스 개발

---

src/main/java/com/example/villagerservice/VillagerServiceApplication.java
src/main/java/com/example/villagerservice/post/api/PostApiController.java
src/main/java/com/example/villagerservice/post/domain/Post.java
src/main/java/com/example/villagerservice/post/exception/PostErrorCode.java
src/main/java/com/example/villagerservice/post/service/PostService.java
src/main/java/com/example/villagerservice/post/service/impl/PostServiceImpl.java

삭제시 게시글상태 false-> true변경후 
매일 23시59분59초마다
스케쥴링체크 5일뒤에 DB삭제 (오차시간포함+1일)   
LocalDateTime.now().minusDays(6);

동네 게시글 삭제 (스케쥴링 구현)

---

src/main/java/com/example/villagerservice/post/api/PostApiController.java
src/main/java/com/example/villagerservice/post/domain/Comment.java
src/main/java/com/example/villagerservice/post/domain/CommentRepository.java
src/main/java/com/example/villagerservice/post/dto/CommentPost.java
src/main/java/com/example/villagerservice/post/dto/ListPost.java
src/main/java/com/example/villagerservice/post/dto/UpdatePost.java
src/main/java/com/example/villagerservice/post/service/CommentService.java
src/main/java/com/example/villagerservice/post/service/PostService.java
src/main/java/com/example/villagerservice/post/service/impl/PostServiceImpl.java
src/main/java/com/example/villagerservice/post/service/impl/commentServiceImpl.java

동네 게시글 댓글 작성하기 서비스v1 개발

---

src/main/java/com/example/villagerservice/config/security/LocalSecurityConfig.java
src/main/java/com/example/villagerservice/config/security/SecurityConfig.java
src/main/java/com/example/villagerservice/config/security/filters/JwtAuthenticationFilter.java
src/main/java/com/example/villagerservice/config/security/properties/CorsProperties.java
src/main/java/com/example/villagerservice/post/api/PostApiController.java
src/main/java/com/example/villagerservice/post/domain/Post.java
src/main/java/com/example/villagerservice/post/domain/PostQueryRepository.java
src/main/java/com/example/villagerservice/post/dto/ListPostItem.java
src/main/java/com/example/villagerservice/post/dto/ListPostSearchCond.java
src/main/java/com/example/villagerservice/post/infra/PostQueryRepositoryImpl.java
src/main/java/com/example/villagerservice/post/service/PostQueryService.java
src/main/java/com/example/villagerservice/post/service/impl/PostQueryServiceImpl.java
src/test/java/com/example/villagerservice/party/api/PartyApiControllerTest.java

게시글 좋아요 목록 조회

---

src/main/java/com/example/villagerservice/member/domain/Member.java
src/main/java/com/example/villagerservice/member/domain/MemberDetail.java
src/main/java/com/example/villagerservice/member/dto/CreateMember.java
src/main/java/com/example/villagerservice/member/dto/UpdateMemberInfo.java
src/main/java/com/example/villagerservice/member/service/impl/MemberServiceImpl.java
src/main/java/com/example/villagerservice/member/valid/Birth.java
src/main/java/com/example/villagerservice/member/valid/BirthValidator.java
src/main/java/com/example/villagerservice/post/api/PostApiController.java
src/main/java/com/example/villagerservice/post/service/impl/PostServiceImpl.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerTest.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java

- 회원 등록 시 생년월일 부분 수정, 자기소개 필드 추가
- 회원 정보 변경 기능 수정
- 회원 등록 테스트 수정
- 회원 정보 변경 테스트 수정

회원 등록 및 회원 정보 변경 기능 추가

---

src/main/java/com/example/villagerservice/post/api/PostApiController.java
src/main/java/com/example/villagerservice/post/domain/Post.java
src/main/java/com/example/villagerservice/post/domain/PostComment.java
src/main/java/com/example/villagerservice/post/domain/PostCommentRepository.java
src/main/java/com/example/villagerservice/post/domain/PostQueryRepository.java
src/main/java/com/example/villagerservice/post/dto/PostCommentItem.java
src/main/java/com/example/villagerservice/post/dto/PostImageItem.java
src/main/java/com/example/villagerservice/post/dto/PostItemDetail.java
src/main/java/com/example/villagerservice/post/infra/PostQueryRepositoryImpl.java
src/main/java/com/example/villagerservice/post/service/PostCommentService.java
src/main/java/com/example/villagerservice/post/service/PostQueryService.java
src/main/java/com/example/villagerservice/post/service/PostService.java
src/main/java/com/example/villagerservice/post/service/impl/FileUploadServiceImpl.java
src/main/java/com/example/villagerservice/post/service/impl/PostCommentServiceImpl.java
src/main/java/com/example/villagerservice/post/service/impl/PostQueryServiceImpl.java
src/main/java/com/example/villagerservice/post/service/impl/PostServiceImpl.java
src/main/resources/application.yml

게시글 상세 조회 api 추가

---

src/main/java/com/example/villagerservice/post/dto/UpdatePostComment.java
src/test/java/com/example/villagerservice/post/api/PostApiControllerIntegratedTest.java

게시글 댓글 변경 통합 테스트 작성

---

src/main/java/com/example/villagerservice/member/api/MemberApiController.java
src/main/java/com/example/villagerservice/member/domain/MemberDetail.java
src/main/java/com/example/villagerservice/member/domain/MemberQueryRepository.java
src/main/java/com/example/villagerservice/member/dto/MemberDetail.java
src/main/java/com/example/villagerservice/member/infra/MemberQueryRepositoryImpl.java
src/main/java/com/example/villagerservice/member/service/MemberQueryService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberQueryServiceImpl.java
src/test/java/com/example/villagerservice/config/BaseLogin.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberQueryServiceImplTest.java

- 회원 마이페이지 조회 서비스 개발
- 회원 마이페이지 조회 테스트 작성

회원 마이페이지 조회 서비스 개발

---

src/main/java/com/example/villagerservice/post/api/PostApiController.java
src/main/java/com/example/villagerservice/post/domain/CategoryRepository.java
src/main/java/com/example/villagerservice/post/dto/CategoryDto.java
src/main/java/com/example/villagerservice/post/service/PostService.java
src/main/java/com/example/villagerservice/post/service/impl/PostServiceImpl.java

동네 게시글 카테고리 전체조회
유효한 카테고리만 보여주기 (boolean isVisible = true)

동네 게시글 카테고리 전체조회 개발

---

build.gradle
src/main/java/com/example/villagerservice/VillagerServiceApplication.java
src/main/java/com/example/villagerservice/config/events/Event.java
src/main/java/com/example/villagerservice/config/events/EventProducer.java
src/main/java/com/example/villagerservice/config/events/EventType.java
src/main/java/com/example/villagerservice/config/events/Events.java
src/main/java/com/example/villagerservice/config/events/EventsConfig.java
src/main/java/com/example/villagerservice/config/rabbitmq/RabbitmqConfig.java
src/main/java/com/example/villagerservice/party/domain/PartyCreatedEvent.java
src/main/java/com/example/villagerservice/party/handler/PartyCreatedEventHandler.java
src/main/java/com/example/villagerservice/party/service/impl/PartyServiceImpl.java
src/main/resources/application.yml
src/test/java/com/example/villagerservice/postlike/api/PostLikeApiControllerIntegratedTest.java

- RabbitMQ 라이브러리 추가
- 모임 생성 시 이벤트 발생 로직 추가

모임 생성 시 이벤트 발생 로직 추가

---

src/main/java/com/example/villagerservice/common/jwt/JwtTokenResponse.java
src/main/java/com/example/villagerservice/config/security/handler/CustomSuccessHandler.java
src/main/java/com/example/villagerservice/member/api/AuthApiController.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerIntegratedTest.java

- JwtTokenResponse 응답 dto 에 로그인한 회원 id 추가
- 로그인 테스트 수정

로그인 시 JwtTokenResponse 응답 dto에 필드 추가

---

src/main/java/com/example/villagerservice/commenttemplates/api/commentTemplateController.java
src/main/java/com/example/villagerservice/commenttemplates/domain/CommentTemplate.java
src/main/java/com/example/villagerservice/commenttemplates/domain/CommentTemplateQueryRepository.java
src/main/java/com/example/villagerservice/commenttemplates/dto/CommentTemplateDto.java
src/main/java/com/example/villagerservice/commenttemplates/dto/CommentTemplateItemDto.java
src/main/java/com/example/villagerservice/commenttemplates/infra/CommentTemplateQueryRepositoryImpl.java
src/main/java/com/example/villagerservice/commenttemplates/service/CommentTemplateQueryService.java
src/main/java/com/example/villagerservice/commenttemplates/service/CommentTemplateQueryServiceImpl.java
src/main/resources/database/local/data.sql

commentTemplateQueryService.getCommentTemplateList()

후기탬플릿 리스트 조회

---

src/main/java/com/example/villagerservice/member/api/MemberTownApiController.java
src/main/java/com/example/villagerservice/member/domain/MemberTown.java
src/main/java/com/example/villagerservice/member/domain/MemberTownRepository.java
src/main/java/com/example/villagerservice/member/dto/MemberTownListItem.java
src/main/java/com/example/villagerservice/member/dto/UpdateMemberTown.java
src/main/java/com/example/villagerservice/member/infra/MemberTownQueryRepositoryImpl.java
src/main/java/com/example/villagerservice/member/service/MemberTownService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberTownServiceImpl.java
src/test/java/com/example/villagerservice/member/api/MemberTownApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/api/MemberTownApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberTownQueryServiceImplTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberTownServiceImplTest.java

- 동네회원 조회 시 main 필드 추가
- 동네회원 수정 시 main 필드 변경 기능 추가

동네회원 조회 및 변경 수정

---

src/main/java/com/example/villagerservice/member/domain/Birthday.java
src/main/java/com/example/villagerservice/member/domain/Gender.java
src/main/java/com/example/villagerservice/member/dto/MemberDetail.java
src/main/java/com/example/villagerservice/member/infra/MemberQueryRepositoryImpl.java
src/test/java/com/example/villagerservice/config/BaseLogin.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerIntegratedTest.java

회원 마이페이지 조회 시 필드 추가

---

src/main/java/com/example/villagerservice/member/api/MemberApiController.java
src/main/java/com/example/villagerservice/member/domain/Member.java
src/main/java/com/example/villagerservice/member/dto/PasswordValid.java
src/main/java/com/example/villagerservice/member/service/MemberService.java
src/main/java/com/example/villagerservice/member/service/impl/MemberServiceImpl.java
src/test/java/com/example/villagerservice/member/api/MemberApiControllerIntegratedTest.java
src/test/java/com/example/villagerservice/member/domain/MemberTest.java
src/test/java/com/example/villagerservice/member/service/impl/MemberServiceImplTest.java

- 회원 비밀번호 검증 api 개발
- 회원 비밀번호 검증 테스트 작성

회원 비밀번호 검증 api 개발

---

src/main/java/com/example/villagerservice/common/jwt/JwtTokenProvider.java
src/main/java/com/example/villagerservice/config/redis/RedisRepositoryImpl.java
src/main/java/com/example/villagerservice/config/security/LocalSecurityConfig.java
src/main/java/com/example/villagerservice/config/security/SecurityConfig.java
src/main/java/com/example/villagerservice/config/security/filters/JwtAuthenticationFilter.java
src/main/java/com/example/villagerservice/config/security/handler/CustomSuccessHandler.java
src/main/java/com/example/villagerservice/config/security/oauth2/model/PrincipalUser.java
src/main/java/com/example/villagerservice/config/security/oauth2/service/AbstractOAuth2UserService.java
src/main/java/com/example/villagerservice/config/security/oauth2/service/CustomOAuth2UserService.java
src/main/java/com/example/villagerservice/config/security/oauth2/service/CustomOidcUserService.java
src/main/java/com/example/villagerservice/config/security/oauth2/service/OAuth2MemberService.java
src/main/java/com/example/villagerservice/member/api/AuthApiController.java
src/main/java/com/example/villagerservice/member/domain/Member.java
src/test/java/com/example/villagerservice/config/AuthConfig.java
src/test/java/com/example/villagerservice/member/api/AuthApiControllerTest.java
src/test/java/com/example/villagerservice/member/service/impl/OAuth2MemberServiceImplTest.java

- OAuth2.0 구글 로그인 개발
- JWT Token Provider 분기처리(PrinciplaUser)

OAuth2.0 구글 로그인 개발
